### ISSUE TITLE
duration.isValid is not a function

### ISSUE THREAD

**Issue by smashwilson** [smashwilson/hubot-plan#11]
Seen when trying to propose `2017-12-15T21:00:00+2h`:

```
TypeError: duration.isValid is not a function
    at Function.parse (/usr/src/app/node_modules/hubot-plan/lib/timespan.js:93:30)
    at EventManipulator.handleProposeArg (/usr/src/app/node_modules/hubot-plan/lib/commands/helpers.js:65:27)
    at handler (/usr/src/app/node_modules/hubot-plan/lib/commands/edit.js:123:15)
    at robot.hubot-events.withStore (/usr/src/app/node_modules/hubot-plan/lib/commands/index.js:11:19)
    at Object.withStore (/usr/src/app/node_modules/hubot-plan/lib/index.js:32:15)
    at Object.argv [as handler] (/usr/src/app/node_modules/hubot-plan/lib/commands/index.js:8:31)
    at Object.runCommand (/usr/src/app/node_modules/yargs/lib/command.js:228:22)
    at Object.parseArgs [as _parseArgs] (/usr/src/app/node_modules/yargs/yargs.js:1023:28)
    at Object.parse (/usr/src/app/node_modules/yargs/yargs.js:542:25)
    at TextListener.callback (/usr/src/app/node_modules/hubot-plan/lib/index.js:67:7)
    at /usr/src/app/node_modules/hubot/src/listener.coffee:65:12
    at allDone (/usr/src/app/node_modules/hubot/src/middleware.coffee:44:37)
    at /usr/src/app/node_modules/hubot/node_modules/async/lib/async.js:274:13
    at Object.async.eachSeries (/usr/src/app/node_modules/hubot/node_modules/async/lib/async.js:142:20)
    at Object.async.reduce (/usr/src/app/node_modules/hubot/node_modules/async/lib/async.js:268:15)
    at /usr/src/app/node_modules/hubot/src/middleware.coffee:49:13
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by smashwilson** [comment]
Fixed with a moment upgrade.
